### ISSUE TITLE
Update LyceumMuJoCoViz and port it to a package extension in this package

### ISSUE THREAD

**Issue by JamieMair** [JamieMair/MuJoCo.jl#34]
Follows this PR - https://github.com/JamieMair/MuJoCo.jl/pull/17

## Todo
- [x] Copy over files from https://github.com/Lyceum/LyceumMuJoCoViz.jl into the package extension
- [x] Change all `Ref` to using our custom wrapper structs
- [x] Change all string setting to use the new `set_string!` function instead
- [x] Make sure all the dependencies are added
- [x] Remove any unnecessary frees on wrapped objects
- [x] Write a minimal amount of documentation on how to use the visualiser, mostly to document it's features
- [x] Perform tests on our platforms to make sure it works.

**Comment by JamieMair** [comment]
I have just added the skeleton of some code to be able to start adding in the full visualiser. There should be enough examples in this of how to add additional dependencies to the project.
# Steps to add a new dependency:
- Search for one of the current deps like `GLFW` and add the new dep everywhere GLFW appears
- Make sure the revise code is updated for backwards compatibility

**Comment by nic-barbara** [comment]
There are a few features in `LyceumMuJoCoViz.jl` that we might want to ignore:
- Pressing `backspace` resets the model if a [`reset!()`](https://github.com/Lyceum/LyceumMuJoCo.jl/blob/master/src/abstractmujocoenvironment.jl#L49) method is defined.
- The `Trajectory` visualisation mode relies on the states of a model being defined. In the past, they used [`setstate!()`](https://github.com/Lyceum/LyceumMuJoCo.jl/blob/master/src/abstractmujocoenvironment.jl#L28) and [`getstate!()`](https://github.com/Lyceum/LyceumMuJoCo.jl/blob/master/src/abstractmujocoenvironment.jl#L23) for different MuJoCo environments.

Each of these methods will vary depending on the MuJoCo environment. It made sense in the original wrapper because the models were custom "environments", where each environments had `reset!()`, `getstate!()`, and `setstate!()` defined for it. In our case, we're providing a general visualiser for MuJoCo models that may not have these methods.

I've left the old trajectory and reverse-stepping code commented out for now. We can implement them later if we think of a good way to approach the problem.
