### ISSUE TITLE
Create wrapper for the mjModel and mjData structs

### ISSUE THREAD

**Issue by JamieMair** [JamieMair/MuJoCo.jl#4]
- [x] Use [`Clang.jl`](https://github.com/JuliaInterop/Clang.jl) to autogen structs and enums
- [x] Clean up the code written by `Clang.jl`
- [x] Make a script to clone the original mujoco repository
- [x] Using PyCall to parse the introspect autogenerated files for the description
- [x] Convert the python AST objects to Julia ones 
- [x] Use the documented objects to comment Clang generated data
- [x] Write a basic test which loads a model and steps it using the autogenerated code
- [x] Create API wrappers for the internal objects such as `Model` and `Data` (see https://github.com/JamieMair/MuJoCo.jl/issues/7)
- [x] Create a basic binding wrapper for accessing via `getproperty` to directly access the underlying data
- [x] If structs contain fields with wrapped structs, return the wrapped struct
- [x] Create a binding wrapper that allows for writing to structs via pointers
- [x] Add a way to access the array properties via an UnsafeArray or equivalent
- [x] Remove comments for structs with no docs

# Tasks to be moved to another PR
- Clean up the final `gen` folder and separate the scripts into different files
- Add in a better way to remove the expressions generated by `Clang.jl`
- Wrap fields which are pointers to their array counterparts when the docs indicate that it is an array

**Comment by JamieMair** [comment]
Added in changes in https://github.com/JamieMair/MuJoCo.jl/pull/6
