### ISSUE TITLE
Go through the example script and add relevant functionality to make the API more user friendly

### ISSUE THREAD

**Issue by JamieMair** [JamieMair/MuJoCo.jl#61]
Go through https://github.com/JamieMair/MuJoCo.jl/pull/57 and note which improvements should be made to make this user friendly.

# TODO
- [x] Add a way to create row-major arrays easily
- [ ] ~~Think about how to wrap functions to be easily used from within Julia - this may need to be a separate PR~~
- [x] Add in some functions to get the names of all joints or bodies etc
- [ ] ~~Fix performance hits from global variables with the function - possibly introduce a functor~~

**Comment by JamieMair** [comment]
https://github.com/JamieMair/MuJoCo.jl/issues/50 should keep track of todo 2 here, easier to remove it from scope for now.

**Comment by JamieMair** [comment]
The final todo can wait until later. I have created https://github.com/JamieMair/MuJoCo.jl/issues/66 to track this issue.
